[theme]
base="light"
primaryColor="#2f3ccf"
backgroundColor="#eeeeee"
secondaryBackgroundColor="#dddddd"
textColor="#2f3ccf"
font="sans serif"

[server]
maxUploadSize=25

[client]
showSidebarNavigation = false